/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffScannerRouteImport } from './routes/staff/scanner'
import { Route as GuestPassTokenRouteImport } from './routes/guest-pass.$token'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScanLogsRouteImport } from './routes/admin.scan-logs'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRenewalsRouteImport } from './routes/admin.renewals'
import { Route as AdminPlanConfigRouteImport } from './routes/admin.plan-config'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminHeadcountRouteImport } from './routes/admin.headcount'
import { Route as AdminGuestPassesRouteImport } from './routes/admin.guest-passes'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffScannerRoute = StaffScannerRouteImport.update({
  id: '/staff/scanner',
  path: '/staff/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestPassTokenRoute = GuestPassTokenRouteImport.update({
  id: '/guest-pass/$token',
  path: '/guest-pass/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanLogsRoute = AdminScanLogsRouteImport.update({
  id: '/scan-logs',
  path: '/scan-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRenewalsRoute = AdminRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanConfigRoute = AdminPlanConfigRouteImport.update({
  id: '/plan-config',
  path: '/plan-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeadcountRoute = AdminHeadcountRouteImport.update({
  id: '/headcount',
  path: '/headcount',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestPassesRoute = AdminGuestPassesRouteImport.update({
  id: '/guest-passes',
  path: '/guest-passes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/guest-passes': typeof AdminGuestPassesRoute
  '/admin/headcount': typeof AdminHeadcountRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plan-config': typeof AdminPlanConfigRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scan-logs': typeof AdminScanLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
  '/staff/scanner': typeof StaffScannerRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/guest-passes': typeof AdminGuestPassesRoute
  '/admin/headcount': typeof AdminHeadcountRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plan-config': typeof AdminPlanConfigRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scan-logs': typeof AdminScanLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
  '/staff/scanner': typeof StaffScannerRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/guest-passes': typeof AdminGuestPassesRoute
  '/admin/headcount': typeof AdminHeadcountRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plan-config': typeof AdminPlanConfigRoute
  '/admin/renewals': typeof AdminRenewalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scan-logs': typeof AdminScanLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/guest-pass/$token': typeof GuestPassTokenRoute
  '/staff/scanner': typeof StaffScannerRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refunds'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin/analytics'
    | '/admin/feedback'
    | '/admin/finance'
    | '/admin/guest-passes'
    | '/admin/headcount'
    | '/admin/members'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plan-config'
    | '/admin/renewals'
    | '/admin/reports'
    | '/admin/scan-logs'
    | '/admin/settings'
    | '/admin/staff'
    | '/guest-pass/$token'
    | '/staff/scanner'
    | '/admin/'
    | '/member/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refunds'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin/analytics'
    | '/admin/feedback'
    | '/admin/finance'
    | '/admin/guest-passes'
    | '/admin/headcount'
    | '/admin/members'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plan-config'
    | '/admin/renewals'
    | '/admin/reports'
    | '/admin/scan-logs'
    | '/admin/settings'
    | '/admin/staff'
    | '/guest-pass/$token'
    | '/staff/scanner'
    | '/admin'
    | '/member'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refunds'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin/analytics'
    | '/admin/feedback'
    | '/admin/finance'
    | '/admin/guest-passes'
    | '/admin/headcount'
    | '/admin/members'
    | '/admin/menu'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plan-config'
    | '/admin/renewals'
    | '/admin/reports'
    | '/admin/scan-logs'
    | '/admin/settings'
    | '/admin/staff'
    | '/guest-pass/$token'
    | '/staff/scanner'
    | '/admin/'
    | '/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  GuestPassTokenRoute: typeof GuestPassTokenRoute
  StaffScannerRoute: typeof StaffScannerRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/scanner': {
      id: '/staff/scanner'
      path: '/staff/scanner'
      fullPath: '/staff/scanner'
      preLoaderRoute: typeof StaffScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-pass/$token': {
      id: '/guest-pass/$token'
      path: '/guest-pass/$token'
      fullPath: '/guest-pass/$token'
      preLoaderRoute: typeof GuestPassTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan-logs': {
      id: '/admin/scan-logs'
      path: '/scan-logs'
      fullPath: '/admin/scan-logs'
      preLoaderRoute: typeof AdminScanLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/renewals': {
      id: '/admin/renewals'
      path: '/renewals'
      fullPath: '/admin/renewals'
      preLoaderRoute: typeof AdminRenewalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plan-config': {
      id: '/admin/plan-config'
      path: '/plan-config'
      fullPath: '/admin/plan-config'
      preLoaderRoute: typeof AdminPlanConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/headcount': {
      id: '/admin/headcount'
      path: '/headcount'
      fullPath: '/admin/headcount'
      preLoaderRoute: typeof AdminHeadcountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guest-passes': {
      id: '/admin/guest-passes'
      path: '/guest-passes'
      fullPath: '/admin/guest-passes'
      preLoaderRoute: typeof AdminGuestPassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGuestPassesRoute: typeof AdminGuestPassesRoute
  AdminHeadcountRoute: typeof AdminHeadcountRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlanConfigRoute: typeof AdminPlanConfigRoute
  AdminRenewalsRoute: typeof AdminRenewalsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScanLogsRoute: typeof AdminScanLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGuestPassesRoute: AdminGuestPassesRoute,
  AdminHeadcountRoute: AdminHeadcountRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlanConfigRoute: AdminPlanConfigRoute,
  AdminRenewalsRoute: AdminRenewalsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScanLogsRoute: AdminScanLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  GuestPassTokenRoute: GuestPassTokenRoute,
  StaffScannerRoute: StaffScannerRoute,
  MemberIndexRoute: MemberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
