/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffScannerRouteImport } from './routes/staff/scanner'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminScanLogsRouteImport } from './routes/admin.scan-logs'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPlanConfigRouteImport } from './routes/admin.plan-config'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffScannerRoute = StaffScannerRouteImport.update({
  id: '/staff/scanner',
  path: '/staff/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanLogsRoute = AdminScanLogsRouteImport.update({
  id: '/scan-logs',
  path: '/scan-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanConfigRoute = AdminPlanConfigRouteImport.update({
  id: '/plan-config',
  path: '/plan-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plan-config': typeof AdminPlanConfigRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scan-logs': typeof AdminScanLogsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/staff/scanner': typeof StaffScannerRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plan-config': typeof AdminPlanConfigRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scan-logs': typeof AdminScanLogsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/staff/scanner': typeof StaffScannerRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plan-config': typeof AdminPlanConfigRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scan-logs': typeof AdminScanLogsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/staff/scanner': typeof StaffScannerRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/finance'
    | '/admin/members'
    | '/admin/payments'
    | '/admin/plan-config'
    | '/admin/reports'
    | '/admin/scan-logs'
    | '/admin/staff'
    | '/staff/scanner'
    | '/admin/'
    | '/member/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/finance'
    | '/admin/members'
    | '/admin/payments'
    | '/admin/plan-config'
    | '/admin/reports'
    | '/admin/scan-logs'
    | '/admin/staff'
    | '/staff/scanner'
    | '/admin'
    | '/member'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/finance'
    | '/admin/members'
    | '/admin/payments'
    | '/admin/plan-config'
    | '/admin/reports'
    | '/admin/scan-logs'
    | '/admin/staff'
    | '/staff/scanner'
    | '/admin/'
    | '/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StaffScannerRoute: typeof StaffScannerRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/scanner': {
      id: '/staff/scanner'
      path: '/staff/scanner'
      fullPath: '/staff/scanner'
      preLoaderRoute: typeof StaffScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan-logs': {
      id: '/admin/scan-logs'
      path: '/scan-logs'
      fullPath: '/admin/scan-logs'
      preLoaderRoute: typeof AdminScanLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plan-config': {
      id: '/admin/plan-config'
      path: '/plan-config'
      fullPath: '/admin/plan-config'
      preLoaderRoute: typeof AdminPlanConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlanConfigRoute: typeof AdminPlanConfigRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScanLogsRoute: typeof AdminScanLogsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinanceRoute: AdminFinanceRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlanConfigRoute: AdminPlanConfigRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScanLogsRoute: AdminScanLogsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StaffScannerRoute: StaffScannerRoute,
  MemberIndexRoute: MemberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
